name: Build
on: [push, workflow_dispatch]
jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22 # This fixes the 'Fatal' error from your logs
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build Web
        run: npx vite build
      - name: Sync Android
        run: npx cap sync android
      - name: Build Bundle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: android/app/build/outputs/bundle/release/*.aab
          
